name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: build-server

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: hostname
  deploy:
    runs-on: prod-server
    steps:
    - name: print hostname of the machine
      run: hostname
 
 