name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: build-server

    steps:
    - uses: actions/checkout@v4
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run attempt
      run: echo ${{ github.run_attempt }}
    - name: print hostname
      run: hostname
    - name: build docker image
      run: docker build -t test:v1 .
    - name: docker image tag
      run: docker tag test:v1 dbista71/devops:latest
    - name: docker login
      run: docker login -u ${{dbista71@gmail.com}} -p ${{Dop@emrtds2025}}
    - name: docker push
      run: docker push dbista71/devops:latest

    - name: docker image tag
      run: docker tag 
  deploy:
    runs-on: prod-server
    steps:
    - name: print hostname of the machine
      run: hostname
